version: '2'
services:
  mysql:
    image: mysql:8.0.28
    environment:
      MYSQL_DATABASE: kuakedb
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: kuakedbuser
      MYSQL_PASSWORD: kuakedbpass
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    volumes:
      - "./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf"
