version: '2'
services:
  mysql:
    image: mysql:8.0.28
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3306:3306"
    volumes:
      - "./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf"
